- name: Confirm SSM Connectivity
  hosts: ssm_nat,ssm_hosts
  gather_facts: false

  tasks:
    - name: Wait for stable SSM connection
      wait_for_connection:
        timeout: 300
        sleep: 10
        connect_timeout: 20
      register: conn
      retries: 5
      delay: 10
      until: conn is succeeded
