---
- name: Update and Upgrade
  hosts: ssm_hosts,ssm_nat
  serial: 4
  become: true
  gather_facts: false

  pre_tasks:
    - name: Wait for SSM connection
      wait_for_connection:
        timeout: 180
        sleep: 5
        connect_timeout: 10
      register: conn
      retries: 12
      delay: 5
      until: conn is succeeded

  tasks:
    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist
      register: apt_result
      retries: 12
      delay: 5
      until: apt_result is succeeded

    # - name: Install locales-all
    #   ansible.builtin.apt:
    #     name: locales-all
    #     state: present

    # - name: Ensure en_US.UTF-8 locale exists
    #   ansible.builtin.command: locale-gen en_US.UTF-8
    #   changed_when: false
